server:
  port: 8897

spring:
  application:
    name: jwlz-application-sjjczstp
  datasource:
    url: jdbc:dm://121.43.60.137:52360
    username: SYSDBA
    password: SYSDBA
    driver-class-name: dm.jdbc.driver.DmDriver
#    # 使用druid数据源
#    type: com.alibaba.druid.pool.DruidDataSource
#    # 配置获取连接等待超时的时间
#    # 下面为连接池的补充设置，应用到上面所有数据源中
#    # 初始化大小，最小，最大
#    initialSize: 10
#    minIdle: 10
#    maxActive: 1000
#    # 配置获取连接等待超时的时间
#    maxWait: 30000
#    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
#    timeBetweenEvictionRunsMillis: 60000
#    # 配置一个连接在池中最小生存的时间，单位是毫秒
#    minEvictableIdleTimeMillis: 30000
#    validationQuery: select 'x'
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
#    # 打开PSCache，并且指定每个连接上PSCache的大小
#    poolPreparedStatements: true
#    maxPoolPreparedStatementPerConnectionSize: 20
#    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
#    filters: stat,wall,slf4j
#    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
#    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
#    # 合并多个DruidDataSource的监控数据
#    useGlobalDataSourceStat: true


##gStore高级函数方法名称
seniorFun: "cycleboolean,cyclepath,shortestpath,shortestpathlen,khopreachable,khopreachablepath,khopenumerate,bfscount,ppr,closenesscentrality,trianglecounting,select(pfn"

##查询超过节点数量后台计算XY坐标
nodeNum: 2000